### ISSUE TITLE
Consider moving collection package to core

### ISSUE THREAD

**Issue by robertwestbury** [discordjs/discord.js-next#22]
I don't think Collection deserves it's own package for several reasons:

- It's only one file and one test file
- It's never going to be used without the core package anyway (i think)
- It's used by every package, which is what the core package is meant for (again, could be wrong)
- It's very small

This is coming from an outsiders perspective and I could be totally wrong but it seems right to me 👍

**Comment by RDambrosio016** [comment]
I disagree, the points about it being a single file and small are not very relevant in my opinion, and a huge point of focus for djs-next is unit testing, its harder to test collection by itself if it is embedded into core.  
> It's never going to be used without the core package anyway (i think).

Collection is a very useful structure even outside of discord.js, there are certainly benefits of using it by itself in other projects. 

> It's used by every package, which is what the core package is meant for (again, could be wrong)

I doubt things like websocket and rest will use collections, since they should work with the raw data then feed it back to core where packet handlers/other handlers figure out if the data is cached by working with the collections. i dont see websocket returning collections or making any use of them, same with rest

**Comment by Monbrey** [comment]
I've used Collections externally to discord.js in a few of my projects, it's a very useful data structure which delivers the merits of both Maps and Arrays in one.

It belongs as a separate module.

**Comment by robertwestbury** [comment]
Looks like I'm wrong - cheers guys
